[phases.setup]
nixPkgs = ['bun', 'nodejs', 'python3', 'gcc', 'make', 'chromium', 'nss', 'atk', 'at-spi2-atk', 'cups', 'libdrm', 'libxkbcommon', 'libxcomposite', 'libxdamage', 'libxrandr', 'libgbm', 'pango']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run start'

[env]
PORT = '3000' 