[phases.setup]
nixPkgs = ['bun', 'nodejs', 'python3', 'gcc', 'make', 'chromium', 'nss', 'atk', 'cups', 'libdrm', 'libxkbcommon', 'mesa', 'pango', 'xorg.libXcomposite', 'xorg.libXdamage', 'xorg.libXrandr']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run start'

[env]
PORT = '3000' 