[phases.setup]
nixPkgs = ['bun', 'nodejs', 'python3', 'gcc', 'make', 'chromium', 'nss', 'atk', 'at-spi2-core', 'cups', 'libdrm', 'libxkbcommon', 'libXcomposite', 'libXdamage', 'libXrandr', 'mesa', 'pango']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run start'

[env]
PORT = '3000' 