[phases.setup]
nixPkgs = ['bun', 'nodejs', 'python3', 'gcc', 'make']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run start'

[env]
PORT = '3000' 